spring:
  application:
    name: hello-service
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: "*"
greeting: "Привет"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true