server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.uri}
